version: '3.1'
services:
  app:
    container_name: app
    image: app
    build: ./
    ports:
      - "9090:9000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test-project