version: '3.1'
services:
  application:
    container_name: application
    image: app
    build: ./
    ports:
      - "9000:9000"
    depends_on:
      - db
  db:
    container_name: test-project-db
    image: postgres:12.0
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test-project